### ISSUE TITLE
Document libpng-dev requirement

### ISSUE THREAD

**Issue by andy5995** [KaruroChori/vs-fltk#12]
The build fails when libpng-dev isn't installed. This happened to me during docker container testing (Trixie) and when testing the initial CI setup on Noble. The failure happens during linking (multiple undefined reference errors).

```
subprojects/libfltk/README.CMake.txt
298-    the system libraries can typically be used on Linux/Unix.
299:    Note: if any one of libpng or zlib is not found on the system, both
300-    libraries are built using the bundled ones and a warning is issued.
--
804-      automatically if they were built together with FLTK.
805:      The only reason you may need them would be if you used libpng,
806-      libjpeg, or zlib functions directly in your application and need
```

**Comment by andy5995** [comment]
> Temporary fix in [91c83eb](https://github.com/KaruroChori/vs-fltk/commit/91c83eb5503dc3a819de23b342ff5f03e77f467d) to introduce some documentation.

That appears to be a duplicate of 51dc00321c088da09300367a82ae5660286a8cae

**Comment by KaruroChori** [comment]
Right, it was be3176efb334a48d3967c434ae09215935b1fdac

**Comment by KaruroChori** [comment]
Now tracked by https://github.com/KaruroChori/vs-fltk/issues/19
