### ISSUE TITLE
Add libpango requirement to meson build

### ISSUE THREAD

**Issue by andy5995** [KaruroChori/vs-fltk#17]
Related: https://github.com/KaruroChori/vs-fltk/pull/16 and https://github.com/KaruroChori/vs-fltk/issues/12

@KaruroChori Would you like me to do this?

**Comment by KaruroChori** [comment]
I don't think it would be a good idea. `vs` does not really care about the underlying libraries needed by `libfltk` and will never directly interface with any of them.
Having `fltk` built alongside the rest of the application was my mistake, mostly motivated by my need of using its latest 1.4 version.
It is not meant to be statically linked in `vs`, and it will never be forked, contrary to libraries like `libtcc`. 

So the best approach would be to take it out, wrap it in its own package that we could distribute for convenience and to support workflows/images in this repo, and simply require for that to be found on the system for `vs` to be built.

**Comment by KaruroChori** [comment]
For reference, most distributions (like debian) already provide libfltk, but they are stuck at 1.3.9 for good reasons.

**Comment by KaruroChori** [comment]
Tacked by https://github.com/KaruroChori/vs-fltk/issues/19
