### ISSUE TITLE
Make fltk a system dependency

### ISSUE THREAD

**Issue by KaruroChori** [KaruroChori/vs-fltk#19]
`fltk` should be handled as a required system dependency, and if a version >1.4 is provided (subject to future changes if new features are desirable) `vs` is happy.
This removes the need for `vs` to directly handle system & distribution specific dependencies on behalf of fltk.  
A special `.deb` is provided to install the right version of `libfltk-dev` in flatpak and docker images.

https://github.com/KaruroChori/vs-fltk/issues/17 and https://github.com/KaruroChori/vs-fltk/issues/12 are superseded by this issue.

- [x] Add search of fltk dep in `vs` build system.
- [x] Add flag to control if using it is desirable.
- [ ] Wait for upstream rolling of fltk1.4 or start distributing a deb package for it

**Comment by KaruroChori** [comment]
For future reference:
https://groups.google.com/g/mesonbuild/c/kEzh3OsgYXk
https://www.fltk.org/str.php?L2180

Forked fltk should include the pc file to be discoverable.

**Comment by KaruroChori** [comment]
What had to be done within this repo has been. Now we either wait for fltk1.4 to roll down in releases or we just ship our own deb from https://github.com/lazy-eggplant/fltk

**Comment by andy5995** [comment]
I'll finish up https://github.com/andy5995/gh-action-build-deb/pull/12 tomorrow. I think it's almost good to go. Just gotta update the docs, release v2.1.x and change the v2 tag to point to it.

**Comment by andy5995** [comment]
Actually, v1.1.0 will point to v1. I was thinking of a different project.

**Comment by KaruroChori** [comment]
This was mostly fixed as a result of https://github.com/fltk/fltk/discussions/1169#discussioncomment-11578767
These findings have been implemented and will be added to the docs.
