### ISSUE TITLE
`libdir` issues

### ISSUE THREAD

**Issue by KaruroChori** [KaruroChori/vs-fltk#3]
There is a difference in behaviour between the library directory used by meson, and that used by CMake through meson.
On my debian system for example, libraries generated by meson are moved into `/usr/lib/x86...../` which is the right place. CMake via meson instead is placing them in `/usr/lib`.
There is as similar issue on the `freedesktop 24.08` image of flatpak. Meson places its libraries in `/app/lib/` while CMake tries to place them in `/app/lib64` which is wrong.

This issue is preventing the proper installation of `vs` and to build the flatpak image correctly.

- [x] Recreate this issue in a simple reposiotry
- [x] Report it upstream @ https://github.com/mesonbuild/meson
- [ ] Waiting for an upstream resolution

**Comment by andy5995** [comment]
Static linking all the libraries isn't an option?

**Comment by KaruroChori** [comment]
Sadly this is not possible.
I could statically link some libraries like tinycc, quickjs or lua, but in most cases it would be either impractical or outright impossible.

Custom native components are supposed to be lightweight for distribution and to keep a small memory footprint. At the very least they all need to link `libvs-fltk` and `libfltk`; possibly more, as I would like to avoid the need for end users to install further dependencies once `vs` is ready and running on their machine.

**Comment by KaruroChori** [comment]
Demo repo in https://github.com/KaruroChori/meson-report-error

**Comment by KaruroChori** [comment]
Reported as https://github.com/mesonbuild/meson/issues/13931

**Comment by andy5995** [comment]
I hope you don't mind if I give potentially outlandish ideas while trying to brainstorm a solution:

I have a little experience packaging for a few different Linux distributions, and for AppImage creation. In a packaging script, such as FlatHub, would it be possible, feasible, or practical to: after installing, move the libs to their appropriate directories, and then use patchelf to update where the libraries are being looked for? [An example of how I use patchelf for the 0ad AppImage](https://github.com/0ad-matters/0ad-appimage/blob/e177b19262a2278fca7b5881c68cfcc1ef41ae8b/workflow.sh#L133)

**Comment by KaruroChori** [comment]
While possible, those would be more like workarounds. 
Your approach would surely work to get v0.1.1 out of the oven, but it would only delay the point this has to be solved straight few weeks ahead.

In short, the pipeline to patch binaries would be **very** messy if not outright impossible.  
An important part of `vs` are *custom native components*, which are shipped as dynamic libraries and must dynamically link some of those generated in here which are affected by this bug. It is important to stress that native components are not even hosted and distributed by this repo for the most part in final applications.

**Comment by KaruroChori** [comment]
I think I found the issue... it is a bit of a mess, but now what fails is quite clear. I will have to report this to upstream, as the fix has to be done by meson.

So, in brief the problem is `--prefix`. By default meson uses `/usr/local` and this creates a major issue in the path resolution comparing meson with cmake. Why?

From the [official docs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) of cmake
```
LIBDIR

    object code libraries (lib or lib64)

    On Debian, this may be lib/<multiarch-tuple> when [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html#variable:CMAKE_INSTALL_PREFIX) is /usr.
```
Stress on `/usr`. But default meson uses `/usr/local` so the location of the compiled libraries is going to be either `/etc/local/lib` or `/etc/local/lib64`. **HOWEVER** meson still tries to apply the folder name as if the prefix was `/etc` and not `/etc/local` so its own libraries are going in `/etc/local/x64..../lib/` on debian, that is just wrong.

The solution for now is to manually set the prefix to `/usr`, DESTDIR will still override the final path. However meson should solve the lib resolution upstream to address this issue.

**Comment by KaruroChori** [comment]
The libdir issue of base meson and the one with flatpak are totally different.  
In the first case it is meson messing up the libdir name and cmake is right.
In the second case meson gets proper information from the builder, but cmake does not and so cmake is wrong.

CMake has been patched several times to use lib in place of lib64, and yet the case of a meson submodule is not covered.

**Comment by KaruroChori** [comment]
All done, even if they are workaround issues have been filed to address them.

**Comment by KaruroChori** [comment]
Additional context in case anyone else ends up with the same issue.
freedesktop 24.08 removed patches to CMake to automatically installing in the right directory, forcing the problem downstream. Specifying the libdir for cmake projects is not the workaround as far as flatpak is concerned, but the "desired" behaviour.

Clearly it is not, and either this should be enforced by default by meson, or the patch should go back in my opinion, but the problem at least is fully resolved.
