### ISSUE TITLE
sqlite3: Nonexistent build file './src/components/autogen/meson.build'

### ISSUE THREAD

**Issue by andy5995** [KaruroChori/vs-fltk#6]
sqlitecpp| Subproject sqlitecpp finished.

Downloading sqlite3 source from https://www.sqlite.org/2024/sqlite-amalgamation-3460100.zip
Downloading: 100%|██████████████████████████████████████████████████████████████████████████| 2.64M/2.64M 7.96MB/s eta 00:00
Downloading sqlite3 patch from https://wrapdb.mesonbuild.com/v2/sqlite3_3.46.1-1/get_patch
Downloading: 100%|██████████████████████████████████████████████████████████████████████████| 1.69k/1.69k 8.87MB/s eta 00:00

Executing subproject sqlite3 

sqlite3| Project name: sqlite3
sqlite3| Project version: 3.46.1
sqlite3| C compiler for the host machine: ccache cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240910")
sqlite3| C linker for the host machine: cc ld.bfd 2.43.0
sqlite3| Run-time dependency dl found: YES
sqlite3| Library m found: YES
sqlite3| Dependency threads found: YES unknown (cached)
sqlite3| Build targets in project: 94
sqlite3| Subproject sqlite3 finished.

Run-time dependency libcurl found: YES 8.10.1

meson.build:134:0: ERROR: Nonexistent build file './src/components/autogen/meson.build'

**Comment by KaruroChori** [comment]
A significant amount of code, specifications and secondary schemas in this repo are generated as a pre-build step, starting from schemas.
```
bun run codegen
```
should be executed before the first `meson setup`. In theory it would be possible to call this step directly from meson, but I was not sure that was the best approach.

**Comment by KaruroChori** [comment]
Basically my usual workflow in this repo is:
```
bun run codegen #First time it must be codegen, for small schema changes after codegen.quick
bun run meson-setup.clang-release
```
And then
```
bun run vs.example
```
to compile and run vs with a default example (broken right now as I have not yet fully fixed my tcc integration after the updates in the other repo).

**Comment by andy5995** [comment]
Got it! :)

**Comment by KaruroChori** [comment]
If after all that effort you want to at least see something barely running:
```
./build/vs run ./examples/demo-js.xml
```
as quickjs was not affected.
