### ISSUE TITLE
Dockerfile for CI and local testing

### ISSUE THREAD

**Issue by andy5995** [KaruroChori/vs-fltk#7]
Would you like a Dockerfile to create an image that can be used in the CI, and for local testing if anyone wants?

I could also create a workflow that builds and pushes the image to GitHub packages (on this repository).

**Comment by KaruroChori** [comment]
I think that would be a very good idea.
The system requirements needed to build `vs` right now are quite "demanding" for the end user as they don't match what is available on most distributions, and really annoying to setup on new machines :D. 
So a docker image which covers the build environment would be great, and I would really appreciate any help with that.

Most of my personal projects are self-hosted on a gitea instance, so I am not very knowledgable about the more "advanced" features of github to be honest :D.

**Comment by KaruroChori** [comment]
@andy5995 I merged it in the current state as it is probably stable enough to start building on it.
Sadly docker does not like my name :D 

```
 /usr/bin/docker buildx build --cache-from type=registry,ref=ghcr.io/KaruroChori/vs-fltk:build-env-buildcache --cache-to type=registry,ref=ghcr.io/KaruroChori/vs-fltk:build-env-buildcache,mode=max --file ./Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-BO7T7k/build-iidfile-69aa41acf1.txt --attest type=provenance,mode=max,builder-id=https://github.com/KaruroChori/vs-fltk/actions/runs/11953740342/attempts/1 --secret id=GIT_AUTH_TOKEN,src=/home/runner/work/_temp/docker-actions-toolkit-BO7T7k/tmp-2320-ix3c0TGVYFiE --metadata-file /home/runner/work/_temp/docker-actions-toolkit-BO7T7k/build-metadata-494e5a43fe.json https://github.com/KaruroChori/vs-fltk.git#74c633cf75039b4a59c105fe7caa8a7d5e97207b
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
ERROR: failed to solve: failed to configure registry cache exporter: invalid reference format: repository name (KaruroChori/vs-fltk) must be lowercase
Reference
Check build summary support
Error: buildx failed with: ERROR: failed to solve: failed to configure registry cache exporter: invalid reference format: repository name (KaruroChori/vs-fltk) must be lowercase
```

I will have to fix this.

**Comment by KaruroChori** [comment]
Good, I fixed a couple more things. Now it looks like it is just a problem about authentication, which does make sense since I have no account on their registry :D

**Comment by andy5995** [comment]
> @andy5995 I merged it in the current state as it is probably stable enough to start building on it. Sadly docker does not like my name :D

Rude of it.

I would have been surprised if it worked the first time. Never have they worked the first time for me.

I'm not sure about the authentication error yet. I'll start working on it now.

**Comment by andy5995** [comment]
Usually to use a pre-built docker image in the CI, I use the "[container](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container)" keyword, like these three here:

https://github.com/theimpossibleastronaut/rmw/blob/70afe64a29294c04a95e019caa1e99d03489c757/.github/workflows/c-cpp.yml#L45
